import { poppins } from '@/libs/font';
import ThemeRegistry from '@/libs/muiTheme.jsx';
import { useServerAuth } from '@/hooks/auth-server';
import { AuthProvider } from '@/contexts/AuthContext.jsx';
import './globals.css';

export const metadata = {
  title: 'SamplingReview | App',
  description: 'Generated by create next app',
};

async function useServerData() {
  const result = await useServerAuth();

  return {
    token: result?.token || '',
    refreshToken: result?.refreshToken || '',
    auth: result?.auth || null,
    retryToken: result?.retryToken || '',
  };
}

export default async function RootLayout({ children }) {
  const initAuth = await useServerData();

  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <ThemeRegistry>
          <AuthProvider initData={initAuth}>
            {children}
          </AuthProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
