export const phonePrefixes = [
  { id: '+60', name: 'Malaysia' },
  { id: '+65', name: 'Singapore' },
  { id: '+66', name: 'Thailand' },
  { id: '+852', name: 'Indonesia' },
  { id: '+84', name: 'Vietnam' },
  { id: '+86', name: 'China' },
  { id: '+886', name: 'Taiwan' },
  { id: '+655', name: 'Cambodia' },
  { id: '+853', name: 'Macau' },
  { id: '+673', name: 'Brunei' },
  { id: '+63', name: 'Philiphines' },
  { id: '+61', name: 'Australia' },
];

export const states = [
  { id: 'Johor', name: 'Johor' },
  { id: 'Kedah', name: 'Kedah' },
  { id: 'Kelantan', name: 'Kelantan' },
  { id: 'Labuan', name: 'Labuan' },
  { id: 'Melaka', name: 'Melaka' },
  { id: 'Negeri Sembilan', name: 'Negeri Sembilan' },
  { id: 'Pahang', name: 'Pahang' },
  { id: 'Penang', name: 'Penang' },
  { id: 'Perak', name: 'Perak' },
  { id: 'Perlis', name: 'Perlis' },
  { id: 'Putrajaya', name: 'Putrajaya' },
  { id: 'Sabah', name: 'Sabah' },
  { id: 'Sarawak', name: 'Sarawak' },
  { id: 'Selangor', name: 'Selangor' },
  { id: 'Terengganu', name: 'Terengganu' },
  { id: 'Wilayah Persekutuan', name: 'Wilayah Persekutuan' },
];
